$FilePath = "index.html"
$utf8 = New-Object System.Text.UTF8Encoding($false)
$content = [System.IO.File]::ReadAllText($FilePath, $utf8)
$contentLF = $content -replace "
", "
"

function FromB64([string]$b64) {
    $bytes = [System.Convert]::FromBase64String($b64)
    return [System.Text.Encoding]::UTF8.GetString($bytes)
}

# 1. tutorialSteps
$stepSearch = "const tutorialSteps = ["
$stepIdx = $contentLF.IndexOf($stepSearch)
if ($stepIdx -ge 0) {
    $stepEndIdx = $contentLF.IndexOf("];", $stepIdx) + 2
    $oldStepsBlock = $contentLF.Substring($stepIdx, $stepEndIdx - $stepIdx)
    $newStepsBlock = FromB64 "Y29uc3QgdHV0b3JpYWxTdGVwcyA9IFsKICAgICAgICAgICAgewogICAgICAgICAgICAgICAgdGl0bGU6ICcxP+KRo+2AjjogP+uasOuqtCA/772K66awJywKICAgICAgICAgICAgICAgIGJvZHk6ICc/6r6o7JiSID/skpbrv4k/PzxzdHJvbmc+NOmBuuq+qeyTrD8/L3N0cm9uZz4sIDxzdHJvbmc+OOmBuuq+qeyTrD8/L3N0cm9uZz4gPz8/65qw66q055GcPz/rmq7snK0gP+uCheuCqz8/P++9jOu8sT8/PGJyPjxzbWFsbD4/65qw66q0ID0gP+uaruKUgeWqm8KAID/shI7rkpcg5rmy6rOg7IOHP+uNieyKgi48L3NtYWxsPicsCiAgICAgICAgICAgICAgICBhbmNob3I6ICdub3RlUmVzdEJ1dHRvbnMnLAogICAgICAgICAgICAgICAgcGxhY2VtZW50OiAndG9wJwogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICB0aXRsZTogJzI/4pGj7YCOOiA/7Iez66q0ID/vvYrrprAnLAogICAgICAgICAgICAgICAgYm9keTogJz/sh7PrqrQg5Lul6r6p7JO9IDxzdHJvbmc+NOmBuuq+qeuPuT8/L3N0cm9uZz4sIDxzdHJvbmc+OOmBuuq+qeuPuT8/L3N0cm9uZz7nkZw/P+uaruycrSDorbDqs5fsipw/P+irm+u6pOyToyDvp43rmq7rsb4/64yB7IqCLjxicj48c21hbGw+P+yHs+uqtCA9ID/rmq7ilIEgP+uGgeyUoCA/0Ynrkpcg5rmy6rOg7IOHP+uNieyKgi48L3NtYWxsPicsCiAgICAgICAgICAgICAgICBhbmNob3I6ICdub3RlUmVzdEJ1dHRvbnMnLAogICAgICAgICAgICAgICAgcGxhY2VtZW50OiAndG9wJwogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICB0aXRsZTogJzM/4pGj7YCOOiA/PyAuICkg6YG67IiI7JSg5rmyPywKICAgICAgICAgICAgICAgIGJvZHk6ICc/65qw66q0Pz8/7Iez66q055GcPz/vvYw/ID/jhbzsk6wgPHN0cm9uZz5bIC4gXSAoPz88L3N0cm9uZz4g6Liw6r6q65OJPz8/65qu7Jyt6LmC64yB6r2tPz88YnI+P+uor+yToyDpgbrsiIjslKDvp44/5rS5P+a5suqzoOyDhz8/5rmy66qE7JSg5aqbwoAgMS416KubPz/shI/rvLE/7ISP7IqCIScsCiAgICAgICAgICAgICAgICBhbmNob3I6ICdkb3RCdXR0b24nLAogICAgICAgICAgICAgICAgcGxhY2VtZW50OiAndG9wJwogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICB0aXRsZTogJzQ/4pGj7YCOOiDpgbrsiIjsl6vku6U/P+qzjOq7kD/shI3rprAnLAogICAgICAgICAgICAgICAgYm9keTogJz/rmrDrqrTnkZw/P+yEjuygriA/6rOM6ruQP+yEje2ArCA/652V65aO76eOPzxzdHJvbmc+Wz8/6YG67IiI7Jer5LulPzwvc3Ryb25nPiDouLDqvqrrk4k/Pz/rmq7snK0/Pzxicj4/65qu7JytID/skpbqvaY/67eA67izID8/PHN0cm9uZz4/Pz/rmrDrqrQgPz8/Pz/rmrDrqrQgP+ySluq9jDwvc3Ryb25nPua/oT/vp6HikaQ/5r+hPz/rjIDilIM/7ISP6r2tPz8nLAogICAgICAgICAgICAgICAgYW5jaG9yOiAndGllJywKICAgICAgICAgICAgICAgIHBsYWNlbWVudDogJ3RvcCcKICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAgdGl0bGU6ICc1P+KRo+2AjjogPz/nlLHRieuyiSA/44W867yx6LmC64u/66awJywKICAgICAgICAgICAgICAgIGJvZHk6ICc/7JKVPyDvp6LqvqnsjbE/7Iew44iDIDxzdHJvbmc+Wz8/Pz/vp43rjYjrtZIgP++9iuumsF08L3N0cm9uZz4g6Liw6r6q65OJPz8/65qu7JytID8/55Sx0Ynrsok/Pz/jhbzrvLHpgYrrqK/sioIhPGJyPjxzbWFsbD7oq5vshI7rgqwgP9GK6rmuP+yEjuuVsiDvp43rjYnsk6w/Pz/jhbvjiIMgP+OFvOygmT/rqK/qvYwg76eO642J7YWnID8/P+uNieu8sT8/PC9zbWFsbD4nLAogICAgICAgICAgICAgICAgYW5jaG9yOiAncGxheScsCiAgICAgICAgICAgICAgICBwbGFjZW1lbnQ6ICd0b3AnCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgIHRpdGxlOiAnNj/ikaPtgI46ID/shI7ro47nlLHRiOumsOyojO+nnsKAP+qzjOumsCcsCiAgICAgICAgICAgICAgICBib2R5OiAnP+yEjuOBmyA/64KF7KCwP+uNieyToyA/65qu65KXIDxzdHJvbmc+P+KRvO2ImCA/7ISO66OO55Sx0YjrprA8L3N0cm9uZz4gP+uoruuSlyA8c3Ryb25nPj/rv4rmiKo/76eewoA/6rOM66awPC9zdHJvbmc+55GcPz/rmq7snK0/PycsCiAgICAgICAgICAgICAgICBhbmNob3I6ICd1bmRvQ2xlYXInLAogICAgICAgICAgICAgICAgcGxhY2VtZW50OiAnYm90dG9tJwogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICB0aXRsZTogJz/rjYnrloYgP+qzleyUqiDvp43rmq7rsb7mubI/P+q+qeyfviEnLAogICAgICAgICAgICAgICAgYm9keTogJz/Riuu8seeRnD/vp43rjYnrgoA/64yB7IqCID/rn6Y8YnI+P+uMgeygoyA8c3Ryb25nPls/66CeID/rjYnrloYgP+qzleyUqj/shI3rprBdPC9zdHJvbmc+IOi4sOq+quuTiT/sh7DspIggP+yijuq5rj/shI/slKAg5LulwoDpja7qvqrruLMgNC806Kub67qk7JiEIOeUsdGJ67KJPz8/6rOV7JSqIO+njeuaruuxvj8/6LmC64yB6r2tPz8nLAogICAgICAgICAgICAgICAgYW5jaG9yOiAncHJhY3RpY2UnLAogICAgICAgICAgICAgICAgcGxhY2VtZW50OiAnYm90dG9tJwogICAgICAgICAgICB9CiAgICAgICAgXTs="
    $contentLF = $contentLF.Replace($oldStepsBlock, $newStepsBlock)
    Write-Host "1. tutorialSteps replaced OK" -ForegroundColor Green
}

# 2. help button
$helpBtnSearch = '<button id="btn-help-tutorial"'
$helpBtnIdx = $contentLF.IndexOf($helpBtnSearch)
if ($helpBtnIdx -ge 0) {
    $helpBtnEnd = $contentLF.IndexOf('</button>', $helpBtnIdx) + 9
    $oldBtn = $contentLF.Substring($helpBtnIdx, $helpBtnEnd - $helpBtnIdx)
    $newBtn = FromB64 "PGJ1dHRvbiBpZD0iYnRuLWhlbHAtdHV0b3JpYWwiIG9uY2xpY2s9InNob3dUdXRvcmlhbCh0cnVlKSIgY2xhc3M9InRleHQtdG9vbC1idG4gdGV4dC14cyBtZDp0ZXh0LXNtIiB0aXRsZT0iP9GK67yxIOWqm8KAP+uMgOuxtiA/44W865aGIOi5guuLv+umsCI+CiAgICAgICAgICAgICAgICAgICAgPHNwYW4gY2xhc3M9InRleHQtYmFzZSI+P+uxsDwvc3Bhbj4g5aqbwoA/64yA67G2CiAgICAgICAgICAgICAgICA8L2J1dHRvbj4="
    $contentLF = $contentLF.Replace($oldBtn, $newBtn)
    Write-Host "2. help button replaced OK" -ForegroundColor Green
}

# 3. helpSimpleModal remove
$modalSearch = '<div id="helpSimpleModal"'
$modalIdx = $contentLF.IndexOf($modalSearch)
if ($modalIdx -ge 0) {
    $scriptIdx = $contentLF.IndexOf('<script>', $modalIdx)
    if ($scriptIdx -gt $modalIdx) {
        $modalBlock = $contentLF.Substring($modalIdx, $scriptIdx - $modalIdx)
        $contentLF = $contentLF.Replace($modalBlock, "")
        Write-Host "3. helpSimpleModal removed OK" -ForegroundColor Green
    }
}

# 4. drawTieCurve
$tieSearch = "function drawTieCurve("
$tieIdx = $contentLF.IndexOf($tieSearch)
if ($tieIdx -ge 0) {
    $tieEndIdx = $contentLF.IndexOf("function drawAllTies(", $tieIdx)
    $oldTie = $contentLF.Substring($tieIdx, $tieEndIdx - $tieIdx)
    $newTie = FromB64 "ZnVuY3Rpb24gZHJhd1RpZUN1cnZlKGZyb21Ob3RlLCB0b05vdGUsIHN0YWZmWSwgY29sb3IgPSAnIzBmMTcyYScsIGFscGhhID0gMSkgewogICAgICAgICAgICBpZiAoIWZyb21Ob3RlIHx8ICF0b05vdGUpIHJldHVybjsKICAgICAgICAgICAgY29uc3QgZnJvbVggPSBmcm9tTm90ZS54ICsgMTAuNTsKICAgICAgICAgICAgY29uc3QgdG9YID0gdG9Ob3RlLnggLSAxMC41OwogICAgICAgICAgICBpZiAodG9YIDw9IGZyb21YICsgNCkgcmV0dXJuOwoKICAgICAgICAgICAgY29uc3QgeSA9IHN0YWZmWSArIDEyOwogICAgICAgICAgICBjb25zdCB3aWR0aCA9IHRvWCAtIGZyb21YOwogICAgICAgICAgICAvLyA/P+i5guyHsOykiT/shI3tgKwg5rqQ65SE7L62ICjvp6Tskpbrg7wgMjRweCwgP+uNiO2JrCDpja7qvqg/IDAuMzIsIO+npOySlT8gNTJweCkKICAgICAgICAgICAgY29uc3QgZGVwdGggPSBNYXRoLm1heCgyNCwgTWF0aC5taW4oNTIsIHdpZHRoICogMC4zMikpOwoKICAgICAgICAgICAgcmh5dGhtQ3R4LnNhdmUoKTsKICAgICAgICAgICAgcmh5dGhtQ3R4LnN0cm9rZVN0eWxlID0gY29sb3I7CiAgICAgICAgICAgIHJoeXRobUN0eC5nbG9iYWxBbHBoYSA9IGFscGhhOwogICAgICAgICAgICByaHl0aG1DdHgubGluZVdpZHRoID0gMy4yOwogICAgICAgICAgICByaHl0aG1DdHgubGluZUNhcCA9ICdyb3VuZCc7CiAgICAgICAgICAgIHJoeXRobUN0eC5saW5lSm9pbiA9ICdyb3VuZCc7CgogICAgICAgICAgICAvLyDouLDsoo4/Pz/mgKjiiarqvZE/7Iew7KSIID/rnb/qvaY/7ISN7L62IOaAqOOAk+yqpyA/67qk6r2mCiAgICAgICAgICAgIHJoeXRobUN0eC5iZWdpblBhdGgoKTsKICAgICAgICAgICAgcmh5dGhtQ3R4Lm1vdmVUbyhmcm9tWCwgeSk7CiAgICAgICAgICAgIHJoeXRobUN0eC5iZXppZXJDdXJ2ZVRvKAogICAgICAgICAgICAgICAgZnJvbVggKyB3aWR0aCAqIDAuMjIsIHkgKyBkZXB0aCwKICAgICAgICAgICAgICAgIHRvWCAtIHdpZHRoICogMC4yMiwgeSArIGRlcHRoLAogICAgICAgICAgICAgICAgdG9YLCB5CiAgICAgICAgICAgICk7CiAgICAgICAgICAgIHJoeXRobUN0eC5zdHJva2UoKTsKCiAgICAgICAgICAgIC8vID/rjIHsqLcgPz8/4pGj64K15r+hPz/rmq/ruJk/P+mBuuyIiOyXq+S7pT/oqpjrqbjsu6cg76ed7JW4PwogICAgICAgICAgICByaHl0aG1DdHgubGluZVdpZHRoID0gMS44OwogICAgICAgICAgICByaHl0aG1DdHguZ2xvYmFsQWxwaGEgPSBhbHBoYSAqIDAuNzsKICAgICAgICAgICAgcmh5dGhtQ3R4LmJlZ2luUGF0aCgpOwogICAgICAgICAgICByaHl0aG1DdHgubW92ZVRvKGZyb21YICsgMiwgeSArIDEuNSk7CiAgICAgICAgICAgIHJoeXRobUN0eC5iZXppZXJDdXJ2ZVRvKAogICAgICAgICAgICAgICAgZnJvbVggKyB3aWR0aCAqIDAuMjQsIHkgKyBkZXB0aCAqIDAuODgsCiAgICAgICAgICAgICAgICB0b1ggLSB3aWR0aCAqIDAuMjQsIHkgKyBkZXB0aCAqIDAuODgsCiAgICAgICAgICAgICAgICB0b1ggLSAyLCB5ICsgMS41CiAgICAgICAgICAgICk7CiAgICAgICAgICAgIHJoeXRobUN0eC5zdHJva2UoKTsKCiAgICAgICAgICAgIHJoeXRobUN0eC5yZXN0b3JlKCk7CiAgICAgICAgfQo="
    $contentLF = $contentLF.Replace($oldTie, $newTie)
    Write-Host "4. drawTieCurve replaced OK" -ForegroundColor Green
}

# 5. setTempo
$tempoSearch = "function setTempo(value) {"
$tempoIdx = $contentLF.IndexOf($tempoSearch)
if ($tempoIdx -ge 0) {
    $tempoEndIdx = $contentLF.IndexOf("function setMetronomeEnabled(", $tempoIdx)
    $oldTempo = $contentLF.Substring($tieIdx, $tempoEndIdx - $tempoIdx)
    $oldTempo = $contentLF.Substring($tempoIdx, $tempoEndIdx - $tempoIdx)
    $newTempo = FromB64 "bGV0IF90ZW1wb1Jlc3RhcnRUaW1lciA9IG51bGw7CiAgICAgICAgZnVuY3Rpb24gc2V0VGVtcG8odmFsdWUpIHsKICAgICAgICAgICAgdGVtcG8gPSBNYXRoLm1heCg0MCwgTWF0aC5taW4oMTYwLCBOdW1iZXIodmFsdWUpIHx8IDYwKSk7CiAgICAgICAgICAgIGNvbnN0IHRlbXBvVmFsdWUgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgndGVtcG9WYWx1ZScpOwogICAgICAgICAgICBpZiAodGVtcG9WYWx1ZSkgdGVtcG9WYWx1ZS50ZXh0Q29udGVudCA9ID8/PSBcOwogICAgICAgICAgICB1cGRhdGVQbGF5QnV0dG9uTGFiZWwoKTsKICAgICAgICAgICAgaWYgKGlzUGxheWluZyAmJiAhaXNQcm9qZWN0UGxheWluZykgewogICAgICAgICAgICAgICAgY2xlYXJUaW1lb3V0KF90ZW1wb1Jlc3RhcnRUaW1lcik7CiAgICAgICAgICAgICAgICBfdGVtcG9SZXN0YXJ0VGltZXIgPSBzZXRUaW1lb3V0KGFzeW5jICgpID0+IHsKICAgICAgICAgICAgICAgICAgICBpZiAoaXNQbGF5aW5nICYmICFpc1Byb2plY3RQbGF5aW5nKSB7CiAgICAgICAgICAgICAgICAgICAgICAgIHN0b3BQZXJmb3JtYW5jZSgpOwogICAgICAgICAgICAgICAgICAgICAgICBhd2FpdCBzdGFydFBlcmZvcm1hbmNlKCk7CiAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgfSwgMjAwKTsKICAgICAgICAgICAgfQogICAgICAgIH0K"
    $contentLF = $contentLF.Replace($oldTempo, $newTempo)
    Write-Host "5. setTempo replaced OK" -ForegroundColor Green
}

# 6. showPracticeExample
$practiceSearch = "async function showPracticeExample() {"
$practiceIdx = $contentLF.IndexOf($practiceSearch)
if ($practiceIdx -ge 0) {
    $practiceEndIdx = $contentLF.IndexOf("function startGuidedPractice()", $practiceIdx)
    $oldPractice = $contentLF.Substring($practiceIdx, $practiceEndIdx - $practiceIdx)
    $newPractice = FromB64 "Ly8gP9GK7K2KID8/NC806Kub67qk7JiEID/rjYnrloYg55Sx0Ynrsok6IDTpgbrqvqnsk6w/P+yojCA/P+mBuuq+qeyTrD8/MTbpgbrqvqnsk6w/P+yojCA/65et7JeyPz8z5aqbP+yojCA46YG66r6p7JOsPz846YG66r6p64+5Pz8gICAgICAgIGZ1bmN0aW9uIGdldEZvdXJGb3VyUHJhY3RpY2VFeGFtcGxlKCkgewogICAgICAgICAgICByZXR1cm4gWwogICAgICAgICAgICAgICAgeyB0eXBlOiAncXVhcnRlcicsICAgaXNSZXN0OiBmYWxzZSwgYmVhdE9mZnNldDogMCwgICAgICAgICAgIGRvdHRlZDogZmFsc2UgfSwKICAgICAgICAgICAgICAgIHsgdHlwZTogJ2VpZ2h0aCcsICAgIGlzUmVzdDogZmFsc2UsIGJlYXRPZmZzZXQ6IDEsICAgICAgICAgICBkb3R0ZWQ6IHRydWUgIH0sCiAgICAgICAgICAgICAgICB7IHR5cGU6ICdzaXh0ZWVudGgnLCBpc1Jlc3Q6IGZhbHNlLCBiZWF0T2Zmc2V0OiAxLjc1LCAgICAgICAgZG90dGVkOiBmYWxzZSB9LAogICAgICAgICAgICAgICAgeyB0eXBlOiAndHJpcGxldCcsICAgaXNSZXN0OiBmYWxzZSwgYmVhdE9mZnNldDogMiwgICAgICAgICAgIGRvdHRlZDogZmFsc2UgfSwKICAgICAgICAgICAgICAgIHsgdHlwZTogJ3RyaXBsZXQnLCAgIGlzUmVzdDogZmFsc2UsIGJlYXRPZmZzZXQ6IDIgKyAxLzMsICAgICBkb3R0ZWQ6IGZhbHNlIH0sCiAgICAgICAgICAgICAgICB7IHR5cGU6ICd0cmlwbGV0JywgICBpc1Jlc3Q6IGZhbHNlLCBiZWF0T2Zmc2V0OiAyICsgMi8zLCAgICAgZG90dGVkOiBmYWxzZSB9LAogICAgICAgICAgICAgICAgeyB0eXBlOiAnZWlnaHRoJywgICAgaXNSZXN0OiBmYWxzZSwgYmVhdE9mZnNldDogMywgICAgICAgICAgIGRvdHRlZDogZmFsc2UgfSwKICAgICAgICAgICAgICAgIHsgdHlwZTogJ2VpZ2h0aCcsICAgIGlzUmVzdDogdHJ1ZSwgIGJlYXRPZmZzZXQ6IDMuNSwgICAgICAgICBkb3R0ZWQ6IGZhbHNlIH0KICAgICAgICAgICAgXTsKICAgICAgICB9CgogICAgICAgIGFzeW5jIGZ1bmN0aW9uIHNob3dQcmFjdGljZUV4YW1wbGUoKSB7CiAgICAgICAgICAgIHN0b3BQZXJmb3JtYW5jZSgpOwogICAgICAgICAgICBpZiAodGltZVNpZ25hdHVyZS50b3AgIT09IDQgfHwgdGltZVNpZ25hdHVyZS5ib3R0b20gIT09IDQpIHsKICAgICAgICAgICAgICAgIHNob3dUb2FzdCgnP+yike2ImCA/642J65aGIO+noeyOjOyYiT/CgCA0LzToq5vruqTsmITnkZw/5rmy6rOXPz/sh7DspIggP+KRuOuVsj8/IDQvNOirm+u6pOyYhOa/oT8/66iu66OeID/qvqrshpo/4pG465WyPz8nLCB0cnVlKTsKICAgICAgICAgICAgICAgIGF3YWl0IG5ldyBQcm9taXNlKHIgPT4gc2V0VGltZW91dChyLCA4MDApKTsKICAgICAgICAgICAgICAgIHNldFRpbWVTaWcoNCwgNCk7CiAgICAgICAgICAgICAgICBhd2FpdCBuZXcgUHJvbWlzZShyID0+IHNldFRpbWVvdXQociwgMTAwKSk7CiAgICAgICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgICAgICBzaG93VG9hc3QoJz/rsaYgP+uNieuWhiDvp6HsjozsmIk/woAgNC806Kub67qk7JiE55GcP+a5suqzlz8/7Iew7KSIID/rjYjqtqE/4pG465WyPz8nLCB0cnVlKTsKICAgICAgICAgICAgICAgIGF3YWl0IG5ldyBQcm9taXNlKHIgPT4gc2V0VGltZW91dChyLCA1MDApKTsKICAgICAgICAgICAgfQogICAgICAgICAgICBwdXNoVW5kb1N0YXRlKCk7CiAgICAgICAgICAgIGNvbnN0IGV4YW1wbGUgPSBnZXRGb3VyRm91clByYWN0aWNlRXhhbXBsZSgpOwogICAgICAgICAgICBub3Rlcy5zcGxpY2UoMCwgbm90ZXMubGVuZ3RoLCAuLi5leGFtcGxlLm1hcChub3RlID0+ICh7Li4ubm90ZX0pKSk7CiAgICAgICAgICAgIGd1aWRlZFByYWN0aWNlVGFyZ2V0ID0gZXhhbXBsZS5tYXAobm90ZSA9PiAoey4uLm5vdGV9KSk7CiAgICAgICAgICAgIGRvdENhbmRpZGF0ZU5vdGUgPSBudWxsOwogICAgICAgICAgICBzeW5jQWN0aXZlTWVhc3VyZVN0YXRlKCk7CiAgICAgICAgICAgIGNsb3NlUHJhY3RpY2VQYW5lbCgpOwogICAgICAgICAgICBzaG93UHJhY3RpY2VTdGF0dXMoJ2V4YW1wbGUnKTsKICAgICAgICAgICAgZHJhd0FsbCgpOwogICAgICAgICAgICBzaG93VG9hc3QoJz/rjYnrloY6IDTpgbrqvqnsk6w/P+yojCA/P+mBuuq+qeyTrD8/MTbpgbrqvqnsk6w/P+yojCA/65et7JeyPz8z5aqbP+yojCA46YG66r6p7JOsPz846YG66r6p64+5Pz8sIHRydWUpOwogICAgICAgICAgICBhd2FpdCBzdGFydFBlcmZvcm1hbmNlKCk7CiAgICAgICAgfQo="
    $contentLF = $contentLF.Replace($oldPractice, $newPractice)
    Write-Host "6. showPracticeExample replaced OK" -ForegroundColor Green
}

$finalContent = $contentLF -replace "
", "
"
[System.IO.File]::WriteAllText($FilePath, $finalContent, $utf8)
Write-Host "Applied Base64 patch to index.html cleanly!" -ForegroundColor Green